# Generated by Django 6.0.1 on 2026-02-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_org_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('reviewer', 'Reviewer'), ('vendor', 'Vendor')], default='admin', max_length=20),
        ),
    ]
