# Generated by Django 6.0.1 on 2026-02-03 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ASSIGNED', 'ASSIGNED'), ('SUBMITTED', 'SUBMITTED'), ('APPROVED', 'APPROVED')], default='ASSIGNED', max_length=20)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='templates.template')),
            ],
        ),
    ]
