# Generated by Django 6.0.1 on 2026-02-03 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_add_timestamps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='updated_at',
        ),
    ]
