# Generated by Django 6.0.1 on 2026-02-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_remove_assessment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='assessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='assigned', max_length=20),
        ),
    ]
