# Generated by Django 6.0.1 on 2026-02-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_alter_assessment_options_assessment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='risk_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
