# Generated by Django 6.0.1 on 2026-04-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_alter_assessment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('remediating', 'Remediating'), ('closed', 'Closed'), ('renewed', 'Renewed')], default='assigned', max_length=20),
        ),
    ]
