# Generated by Django 6.0.1 on 2026-02-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_add_code_updatedat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='organization',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
