# Generated by Django 6.0.1 on 2026-02-12 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditevent_delete_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditevent',
            name='timestamp',
        ),
    ]
